### ISSUE TITLE
Possible to deploy binary files

### ISSUE THREAD

**Issue by BurntCaramel** [zeit/now-client#26]
As `now.createDeployment(body, [callback])` expects `body` to be JSON, files can only be text. Is there a way of providing non-textual data here?

**Comment by leo** [comment]
Yep! We'll add this to the docs, you can do this:

```
'filename': {
  binary: true|false,
  content: [DATA]
}
```

Where `[DATA]` is a base64-encoded Buffer of your binary file 😊
