### ISSUE TITLE
Mention async/await examples

### ISSUE THREAD

**Issue by leo** [zeit/now-client#34]
Since we're using Promises, we should prefer these

**Comment by timolins** [comment]
Great idea, async all the way!

**Comment by timolins** [comment]
This should be changed in `README.hbs` since it will automatically overwrite `README.md`.

**Comment by leo** [comment]
We need a different way to handle that! Implementing...

**Comment by leo** [comment]
https://github.com/zeit/now-client/commit/eaa3d69d41744910a392d5b8183cbad6429fb364
