### ISSUE TITLE
Drop support for callbacks

### ISSUE THREAD

**Issue by leo** [zeit/now-client#37]
We shouldn't encourage users to use these. They either need to use Promises directly, or async/await.

**Comment by timolins** [comment]
@rauchg, what is your opinion on that? You seemed to like this feature.

**Comment by leo** [comment]
Callbacks are a relict of old times and Promises are the future. It doesn't harm to leave them in per-se, but it definitely creates more room for bad-looking & slow code.

There's practically no reason to support them anymore. All major browsers + both the LTS and the latest node version support them.

**Comment by timolins** [comment]
1e6fe269b994269f7ecd3bb28d6ab741d9391976 removes support for callbacks. Still need to do some testing and fix the documentation.

**Comment by leo** [comment]
@timolins 😍
