### ISSUE TITLE
Why is --alias option in deploy command deprecated?

### ISSUE THREAD

**Issue by arturmuller** [zeit/now-client#59]
Hey there.

I'm curious why the `--alias` option for the `deploy` command is deprecated?

I understand that it is possible to set aliases through `now.json` now, but to me, these are separate use-cases. Aliasing through the `deploy` command is very handy if you're just trying something out and want to alias it to a different location than the "usual" alias (which would be in `now.json`)

```sh
# Use case for now.json: 
# Deploy to the "usual" alias:

now && now alias

# Use case for "experimenting" alias

# Much more convenient to run this:
now --alias foobar

# Than it is to run:
now
# ...wait until done...
now alias 09duoix0u foobar

# ...or editing now.json
```

I am new to now, so maybe I am doing it all wrong...  🙃 I'd just like to understand the thinking behind the decision to deprecate the command.

Thank you!

**Comment by timolins** [comment]
Hey Artur! I guess this issue should be discussed on [`now-cli`](https://github.com/zeit/now-cli), since this repo is just for the API wrapper itself.

There is a quite similar issue, which could be relevant for you: https://github.com/zeit/now-cli/issues/361

**Comment by arturmuller** [comment]
Great, thanks for pointing me in the right direction!
