### ISSUE TITLE
Add team support

### ISSUE THREAD

**Issue by berzniz** [zeit/now-client#63]
Currently, all API requests are on behalf of the "personal" account. It would be great to read `currentTeam` from `~/.now.json` and use the current team ID for all requests.

**Comment by jkriss** [comment]
It'd be even better if we could pass the team value programmatically, as well.

**Comment by matheuss** [comment]
For reference, that's how it's done in the CLI https://github.com/zeit/now-cli/blob/master/lib/index.js#L851-L858

**Comment by leo** [comment]
Landed! https://github.com/zeit/now-client/pull/66
