### ISSUE TITLE
now.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by drguildo** [zeit/now-client#67]
I tried installing now using the instructions [here](https://zeit.co/download) but whenever I try to run the now command I get an error about it not being a valid Win32 application.

```
PS C:\Users\Simon> npm install -g now
C:\Users\Simon\AppData\Roaming\npm\now -> C:\Users\Simon\AppData\Roaming\npm\node_modules\now\download\dist\now

> now@7.0.2 postinstall C:\Users\Simon\AppData\Roaming\npm\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading now CLI 7.0.2 [====================] 100%
C:\Users\Simon\AppData\Roaming\npm
`-- now@7.0.2

PS C:\Users\Simon> now
Access is denied.
```

![image](https://user-images.githubusercontent.com/9282/27256642-d9bd7904-53b3-11e7-8f4e-20d1e45b0f12.png)

**Comment by leo** [comment]
@igorklopov ^ Perms are striking again 😄

**Comment by leo** [comment]
Oh, btw - @drguildo this should be a [now-cli](https://github.com/zeit/now-cli) issue 😊
