### ISSUE TITLE
getDeployments() doesn't work with teams

### ISSUE THREAD

**Issue by mreinstein** [zeit/now-client#69]
I'm using @remy's excellent https://github.com/remy/now-no-alias module to clean unaliased `now` deploys, but this doesn't work for teams. (it doesn't list any of the deploys associated with domains under a team.) Is there a workaround?

**Comment by leo** [comment]
`now rm --safe`

**Comment by mreinstein** [comment]
@leo this fails for me now@8.2.5 It just prints the help command:

```bash
λ now rm --safe

  𝚫 now remove [...deploymentId|deploymentName]
```
