### ISSUE TITLE
Reformatting code when committing files

### ISSUE THREAD

**Issue by vivekrajr** [zeit/now-client#71]
It made a small change to `lib/index.js` and when I committed the changes, I could see that there is quite a few changes made to the source file, possibly by `npm run -s precommit`. Is this expected behaviour? Is there a way to turn this off? 

Changes can be seen here
https://github.com/zeit/now-client/compare/master...vivekrajr:master

**Comment by TooTallNate** [comment]
I believe that `git commit --no-verify` would skip the precommit hook. Ideally all the source files get prettyified in a separate PR from the changes, to make reading the diff easier.
